services:

  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot_container
    hostname: hostname_telegram_bot
    restart: always
    environment:
      TZ: "Europe/Moscow"
    networks:
      - monitoring_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          memory: 256M
    volumes:
#      - /home/user/Downloads/app:/bot/app
#      - /home/user/Downloads/logger:/bot/logger
      - some_vol:/bot/db

#      - ~/Downloads/app/config_data:/bot/config_data
#    volumes:
#      - type: bind
#        source: /home/user/Downloads/app/var
#        target: /bot/var
#      - /home/user/Downloads/app:/bot/app
#      - some_vol:/bot/config_data
#
volumes:
  some_vol:
    name: bot_vol

networks:
  monitoring_net:
    name: monitoring_net